version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  flask-web-app:
    build: .
    container_name: Flask-web-app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
